// Generated by CoffeeScript 1.6.1
(function() {

  PB.Router.map(function() {
    return this.resource("users", function() {
      return this.route("new", {
        path: "/new"
      });
    });
  });

}).call(this);
